### PR TITLE
Hero accessibility

### PR DESCRIPTION
**Pull request by techeduk8r**
Updated all h1/h2 hero classes for accessibility.

### CODE REVIEW

**Review by lala-laura — COMMENTED** [review]
The only real thing I can add is that for the newer hero h2 classes, a lot have the same values and can have their selectors separated by a comma to free up some space. You may have already tried that and decided this was the way to go. It also might be tedious to go back now since you did a ton of work here (and it looks like it all works really well) so I'm leaving this up to you. Or we can come back to it later, if we have time, in another branch. Otherwise, I'll approve it.

**Comment by techeduk8r** [comment]
@lala-laura Compact code is definitely something I appreciate but what would that look like since .hero-destinations-h2::before refers to and is influenced by the hero-destinations-h2 that proceeds it? If you have an idea, I'll test it.

**Comment by lala-laura** [comment]
Let's leave it, it works and works well!

**Review by lala-laura — APPROVED** [review]
Great job, approving

**Pull request merged**
