### PR TITLE
Instagram

### PR DESCRIPTION
**Pull request by loganmorganml1**
Instagram section made, grid sizes fixed for new review size on mobile

### CODE REVIEW

**Review by lala-laura — COMMENTED** [review]
This push looks like it would remove the hero-subpage css additions and some other needed css from the About page (probably because that was a newer merge). I am thinking we should push and merge the Instagram branch I have first and then add the other-popular-grid edits after. @loganmorganml1 What do you think?

**Comment by loganmorganml1** [comment]
> This push looks like it would remove the hero-subpage css additions and some other needed css from the About page (probably because that was a newer merge). I am thinking we should push and merge the Instagram branch I have first and then add the other-popular-grid edits after. @loganmorganml1 What do you think?

I think Github is being dumb and thinking the older version is a replacement of the new content. Instead I'm going to go in and manually update the code in this branch so we can push it all at once since its not too much. I'll let you know when I've finished updating it.

**Comment by loganmorganml1** [comment]
> > This push looks like it would remove the hero-subpage css additions and some other needed css from the About page (probably because that was a newer merge). I am thinking we should push and merge the Instagram branch I have first and then add the other-popular-grid edits after. @loganmorganml1 What do you think?
> 
> I think Github is being dumb and thinking the older version is a replacement of the new content. Instead I'm going to go in and manually update the code in this branch so we can push it all at once since its not too much. I'll let you know when I've finished updating it.

@lala-laura wait laura I was still working on this

**Comment by lala-laura** [comment]
I saw this comment after, hold on, I'll try to undo @loganmorganml1 

@loganmorganml1 I did undo the commit, I just can't tell if github is reflecting that. Are you okay on your end to proceed?

It was only the urls that were in that merge so if they are written over it's not a big deal

**Comment by loganmorganml1** [comment]
Okay I've cleaned up the issues and we should be good. I did notice that the images for the destinations page is missing though so we'll have to bring those back. Unsure why the links are broken because the images are still there.

**Comment by loganmorganml1** [comment]
Nevermind, fixed the links.

**Review by lala-laura — APPROVED** [review]
There is still some old css here, possibly just inserted with the newer stuff. It looks fine, though, so I'm going approve. I need to make a new branch since I also wasn't 100% done with all the formatting for the larger srcs. If I find old css, I'll remove it from there.

**Comment by loganmorganml1** [comment]
> There is still some old css here, possibly just inserted with the newer stuff. It looks fine, though, so I'm going approve. I need to make a new branch since I also wasn't 100% done with all the formatting for the larger srcs. If I find old css, I'll remove it from there.

sounds good!

**Pull request merged**
