### PR TITLE
Mobile nav edit

### PR DESCRIPTION
**Pull request by lala-laura**
Edits/added style to the mobile drop down menu

### CODE REVIEW

**Comment by techeduk8r** [comment]
@lala-laura this is looking great. Do you feel it's ready to go?

@loganmorganml1 what are your thoughts? Does the design look good to you? If so, let's merge this. 

I did notice an issue with the rotating slideshow in the mobile view, but I'll take a look once this is merged back to main and make any corrections.

**Comment by loganmorganml1** [comment]
> @lala-laura this is looking great. Do you feel it's ready to go?
> 
> @loganmorganml1 what are your thoughts? Does the design look good to you? If so, let's merge this.
> 
> I did notice an issue with the rotating slideshow in the mobile view, but I'll take a look once this is merged back to main and make any corrections.

Looked good to me, I'll merge EDIT hold on before I do, it looks like a bunch of CSS was deleted? would this be deleted if I were to merge this? want to make sure I'm reading this correctly.
Screen Shot 2021-12-05 at 4 18 56 PM

**Comment by lala-laura** [comment]
> > @lala-laura this is looking great. Do you feel it's ready to go?
> > @loganmorganml1 what are your thoughts? Does the design look good to you? If so, let's merge this.
> > I did notice an issue with the rotating slideshow in the mobile view, but I'll take a look once this is merged back to main and make any corrections.
> 
> Looked good to me, I'll merge EDIT hold on before I do, it looks like a bunch of CSS was deleted? would this be deleted if I were to merge this? want to make sure I'm reading this correctly.

Yes, if you both think it looks okay, I think it's good to go.

I noticed some CSS removed and had to rewrite a little on the About page. Would it be best to add some of the non-global CSS to their own files, just for the time being, until we are closer to being finished?

**Comment by loganmorganml1** [comment]
I think its best to keep it in one, since that is standard. Please bring back the CSS deletions and then I'll merge.

**Comment by techeduk8r** [comment]
I’ve been creating separate css files to build but copying the styles to
the style.css file for commits. I’ve had a few things get lost so I’m
keeping my own backups. That way if things go sideways we don’t have to
start over.

**Comment by lala-laura** [comment]
> I think its best to keep it in one, since that is standard. Please bring back the CSS deletions and then I'll merge.

I understand that, but we can add it back to the main style file afterward and maybe avoid some of the clutter and anything happening to any of our CSS going forward. 

I found the css and added it.

**Comment by loganmorganml1** [comment]
> > I think its best to keep it in one, since that is standard. Please bring back the CSS deletions and then I'll merge.
> 
> I understand that, but we can add it back to the main style file afterward and maybe avoid some of the clutter and anything happening to any of our CSS going forward.
> 
> I found the css and added it.
I'm fine as long as the committed branch has all of the CSS. If this one previously was committed it would have deleted a lot of the CSS we have on the main right now.

**Review by loganmorganml1 — APPROVED** [review]
Don't see any issues, approved

**Comment by techeduk8r** [comment]
reopened branch to look at and copy code. Might be needed to restore the nav on main.

**Pull request merged**
