### PR TITLE
book page doesn't want to keep the second dot

### PR DESCRIPTION
**Pull request by lala-laura**
Had to add the second dot to the js script near the bottom of the body.

### CODE REVIEW

**Comment by loganmorganml1** [comment]
@lala-laura wait whats this for? I don't think booking is using any javascript.

**Comment by techeduk8r** [comment]
It doesn't need a second . The directory is only one level up. One . is correct.

**Comment by lala-laura** [comment]
Okay, but it's not working on mobile for the nav

**Comment by loganmorganml1** [comment]
> Okay, but it's not work on mobile for the nav

Ohh I see what you're saying.  I think it does need two, thats what all the other pages have.

**Comment by loganmorganml1** [comment]
@techeduk8r @lala-laura lets push this

**Comment by lala-laura** [comment]
I can't pull this since I pushed it

**Comment by techeduk8r** [comment]
Take a look at the email thread. Assets is one level away which can be seen in all of the img tags. They all reference .assets/img/file name. the JS folder also lives in the Assets folder, so it needs .assets/js/nav.js and index.js. If you still see two .. on other pages, that needs to be fixed. It will prevent the slideshows and nav from working. I'm looking at the live GH page and everything IS working.

**Comment by loganmorganml1** [comment]
> Take a look at the email thread. Assets is one level away which can be seen in all of the img tags. They all reference .assets/img/file name. the JS folder also lives in the Assets folder, so it needs .assets/js/nav.js and index.js. If you still see two .. on other pages, that needs to be fixed. It will prevent the slideshows and nav from working. I'm looking at the live GH page and everything IS working.

The mobile nav isn't working, and just looking at the other pages they all have ..assets/js/nav.js, even `about` which uses two js files with .. and the js for both is still working.

**Comment by loganmorganml1** [comment]
> Take a look at the email thread. Assets is one level away which can be seen in all of the img tags. They all reference .assets/img/file name. the JS folder also lives in the Assets folder, so it needs .assets/js/nav.js and index.js. If you still see two .. on other pages, that needs to be fixed. It will prevent the slideshows and nav from working. I'm looking at the live GH page and everything IS working.

This is for booking, not index. Index uses .assets/img/file name but booking uses ..assets/img/file name

**Comment by loganmorganml1** [comment]
> > Take a look at the email thread. Assets is one level away which can be seen in all of the img tags. They all reference .assets/img/file name. the JS folder also lives in the Assets folder, so it needs .assets/js/nav.js and index.js. If you still see two .. on other pages, that needs to be fixed. It will prevent the slideshows and nav from working. I'm looking at the live GH page and everything IS working.
> 
> This is for booking, not index. Index uses .assets/img/file name but booking uses ..assets/img/file name

Sorry meant to say home, not index

**Comment by techeduk8r** [comment]
Ah! My mistake! Apologies for not making that connection.

**Review by techeduk8r — APPROVED** [review]
Thanks for catching that!

**Pull request merged**
