### PR TITLE
Created where to page

### PR DESCRIPTION
**Pull request by loganmorganml1**
still needs formatting for header, but that is not page specific and should be resolved when merged with main if CSS for h1 sizing is there.

### CODE REVIEW

**Comment by techeduk8r** [comment]
@loganmorganml1  So, I didn't realize the page would look mostly blank when opened and the images only show when you hover over them. Personally, I don't think this is a good design choice for an entire page since it looks unfinished on first glance. What other design ideas could we consider?

I realize this is only on the desktop for the hover. Maybe there are grayscale images in the background like shadows?

@lala-laura What are your thoughts?

**Comment by loganmorganml1** [comment]
> @loganmorganml1 So, I didn't realize the page would look mostly blank when opened and the images only show when you hover over them. Personally, I don't think this is a good design choice for an entire page since it looks unfinished on first glance. What other design ideas could we consider?
> 
> I realize this is only on the desktop for the hover. Maybe there are grayscale images in the background like shadows?
> 
> @lala-laura What are your thoughts?

We could just scrap the hover effect and have the images shown, otherwise we could have it so they are at a low opacity until hovered over. That way they are still visible even without the hover.

**Comment by loganmorganml1** [comment]
> @loganmorganml1 So, I didn't realize the page would look mostly blank when opened and the images only show when you hover over them. Personally, I don't think this is a good design choice for an entire page since it looks unfinished on first glance. What other design ideas could we consider?
> 
> I realize this is only on the desktop for the hover. Maybe there are grayscale images in the background like shadows?
> 
> @lala-laura What are your thoughts?

I've updated with a new hover effect, please review when you get the chance and let me know what you guys think.

**Comment by techeduk8r** [comment]
I think this is more visually appealing and makes clearer what people should do on the page. Thanks for making the change.

**Review by techeduk8r — APPROVED** [review]
Looks great. Approved!

**Pull request merged**
