### PR TITLE
Subpagehero adjustments

### PR DESCRIPTION
**Pull request by lala-laura**
I made a branch with a version with a tighter hero on the subpages. It wasn't as involved as I thought it be and any code that was changed, I commented out so it would still be there so no one lost their original CSS. There is also a note on the html files for each page where I made a section edit.

### CODE REVIEW

**Comment by loganmorganml1** [comment]
Looks good! My only comment is if we are using the same class for the grid on contact and about to rename it. I have no preference as long as it makes sense, you can even name it `contact-and-about-grid` if you want.

@loganmorganml1 I had a similar thought but didn't want to make all the name changes until I knew it worked well for everyone and we'd want to move forward with the pull

**Comment by loganmorganml1** [comment]
> Looks good! My only comment is if we are using the same class for the grid on contact and about to rename it. I have no preference as long as it makes sense, you can even name it `contact-and-about-grid` if you want.
> 
> @loganmorganml1 I had a similar thought but didn't want to make all the name changes until I knew it worked well for everyone and we'd want to move forward with the pull

No worries, sounds good. Just something to note before your pull request to be merged. I'd also add a 50px grid gap for that grid on screens tablet and up.

**Comment by lala-laura** [comment]
@loganmorganml1 @techeduk8r 
The top one or two lines on both the 'book' and 'contact' forms are blocked from having the ability to type within the field in the current 'main branch' when viewed in desktop (I think it was blocked on at least the tablet size for 'book' too). 

This merge looks like it will fix that issue. I'm going to get those couple of class names adjusted and re-reviewed so it's ready for the pull requests.

I'll make a 'clean-up' branch after the merge to remove any commented-out areas referencing this edit, once all is said and done.

**Comment by loganmorganml1** [comment]
> @loganmorganml1 @techeduk8r The top one or two lines on both the 'book' and 'contact' forms are blocked from having the ability to type within the field in the current 'main branch' when viewed in desktop (I think it was blocked on at least the tablet size for 'book' too).
> 
> This merge looks like it will fix that issue. I'm going to get those couple of class names adjusted and re-reviewed so it's ready for the pull requests.
> 
> I'll make a 'clean-up' branch after the merge to remove any commented-out areas referencing this edit, once all is said and done.

thanks for catching that -- if you want you can send a pull request for the code to fix the ability to type in those fields for desktop in a separate branch and I'll merge immediately. That way you can still work on this branch if need be but have that issue fixed.

@loganmorganml1 I have them set here, but this branch should be ready for a review if you have a chance to give it a look.

**Comment by loganmorganml1** [comment]
> > @loganmorganml1 @techeduk8r The top one or two lines on both the 'book' and 'contact' forms are blocked from having the ability to type within the field in the current 'main branch' when viewed in desktop (I think it was blocked on at least the tablet size for 'book' too).
> > This merge looks like it will fix that issue. I'm going to get those couple of class names adjusted and re-reviewed so it's ready for the pull requests.
> > I'll make a 'clean-up' branch after the merge to remove any commented-out areas referencing this edit, once all is said and done.
> 
> thanks for catching that -- if you want you can send a pull request for the code to fix the ability to type in those fields for desktop in a separate branch and I'll merge immediately. That way you can still work on this branch if need be but have that issue fixed.

Nevermind, I just realized that the issue was probably with how the old hero page setup was working and the recoding of the sub-hero has solved that issue

**Review by techeduk8r — APPROVED** [review]
Looks good and resolves all the overhang issues!

**Pull request merged**
