### PR TITLE
Pretty urls

### PR DESCRIPTION
**Pull request by techeduk8r**
Added folders to create pretty urls

### CODE REVIEW

**Review by loganmorganml1 — APPROVED** [review]
Looks good

**Review by loganmorganml1 — APPROVED** [review]
good to go

**Review by loganmorganml1 — APPROVED** [review]
lets merge

**Comment by loganmorganml1** [comment]
@techeduk8r I pulled the code for the `where-to` that Ali did. I don't recall what else is in here, but I think you can delete this if you want.

**Comment by techeduk8r** [comment]
This has been resolved through other means.

**Pull request closed without merging**
