### PR TITLE
changed about button to link

### PR DESCRIPTION
**Pull request by lala-laura**
Removed button type and made 'about-button' a styled link

### CODE REVIEW

**Comment by techeduk8r** [comment]
I know there is debate over whether links should be styled as buttons. If the preference is to go with a button-styled link vs removing the link altogether, I  won't push back. As an FYI, for accessibility, it's good to know that links and buttons are accessed differently, so a button-styled link could be confusing.

**Comment by lala-laura** [comment]
No, that's a good point and one I wasn't totally aware of.  I have no problem with styling a link as a button since I'm used to seeing it that way(the people who designed my work's website do that a ton with links....but there's a lot wrong with that site, so....yeah).  
I'm fine with changing it. Just simple text you think?

**Comment by lala-laura** [comment]
I linked this as text. One thing that's tripping me up: the color is a deep purple and I can't find why. It might be obvious and I'm just not seeing it and maybe I'll figure it out immediately tomorrow, but feel free to get in this code and make the changes you want. It's called 'contact-link' now and I'm not attached to any part of it so change whatever you want.

**Comment by techeduk8r** [comment]
Let's leave this for now and ask Ali how best to handle it. I can send him the error and code and ask how best to resolve it. It's one small error out of all of our pages.

**Comment by loganmorganml1** [comment]
@lala-laura @techeduk8r 
If you want to check I did fix up the link. It looks like our buttons. The issue was you have to call the link with the class, and not just the class for some of the styling on CSS. I've also added some margin for the about-contact grid that just makes the pages look cleaner. 

EDIT: I also put the button in with the about content div, since it was floating outside before.

**Comment by techeduk8r** [comment]
Ali said a link styled as a button is fine. Approving!

**Review by techeduk8r — APPROVED** [review]
Look good.

**Pull request merged**
