### PR TITLE
Where to updates

### PR DESCRIPTION
**Pull request by loganmorganml1**
Added additional CSS and formatting 

-- added in hero and nav

### CODE REVIEW

**Review by lala-laura — COMMENTED** [review]
It looks really good. The only thing I noticed is that when I hover over the images, the color only changes when hovering over the bottom half. Let me know if you want me to approve it and come back to that later or if you want to take a look at it first.

**Comment by loganmorganml1** [comment]
> It looks really good. The only thing I noticed is that when I hover over the images, the color only changes when hovering over the bottom half. Let me know if you want me to approve it and come back to that later or if you want to take a look at it first.

If your referencing the background image color, thats due to the sizing of the images themselves. When they don't take up the entire div, the background color makes up the difference.  I'll try resizing so the images are larger and that doesn't happen.

**Comment by loganmorganml1** [comment]
> It looks really good. The only thing I noticed is that when I hover over the images, the color only changes when hovering over the bottom half. Let me know if you want me to approve it and come back to that later or if you want to take a look at it first.



> > It looks really good. The only thing I noticed is that when I hover over the images, the color only changes when hovering over the bottom half. Let me know if you want me to approve it and come back to that later or if you want to take a look at it first.
> 
> If your referencing the background image color, thats due to the sizing of the images themselves. When they don't take up the entire div, the background color makes up the difference. I'll try resizing so the images are larger and that doesn't happen.

@lala-laura you can merge now, I created another media query for the "where-to" images to accomodate the image size difference at 1440px and 992px

**Review by lala-laura — APPROVED** [review]
Approving

**Pull request merged**
