### PR TITLE
Nav edits

### PR DESCRIPTION
**Pull request by lala-laura**
Nav update push request.
 **Update** draft is turned off, please take a look. I gave it a slight CSS make-over, since adding the nav above the header required adding positions to certain classes since the z-index needs that. Any comment in the CSS that says 'new' is just to find CSS additions that affect code you guys wrote (which was only a couple of spots), but I tried to be thorough to make sure it didn't set anything else off. 

Destinations has a large gap that will need to be adjusted with the header addition to that page.

There is likely stuff I missed, but it's probably smaller style related areas we can go back to. But the formatting and layout should be ready, so we can get this pulled to get the nav set on each page.

### CODE REVIEW

**Comment by loganmorganml1** [comment]
@lala-laura is there are a reason to have different classes for the nav section (ex. `nav-home`, `nav-book`)? You only need one class that can be used throughout.

**Comment by loganmorganml1** [comment]
@lala-laura I would suggest a couple things before this is pushed: 
1. set standard widths for the links in your nav bar so you don't have the jitter with the hover effect, and so that contact isn't pushed all the way to the edge.

2. We are thinking of adding hero images to the pages that the nav bar isn't showing up on, so just copy the code you have for the about page to make it show on those ones.  We can go in and change the titles and images later, but just updating the title would be nice to have when you do that transition. 

3. I think it would be nice to have the active links page bolded. So for example, when you're on booking the booking link is bolded and not just when hovered on. You can do that with a class and assign it to the specific link for the pages your on. 

Let me know if you have any questions on this, I'm available for a call if you'd like to touch base.

**Review by loganmorganml1 — CHANGES_REQUESTED** [review]
See comments

**Comment by lala-laura** [comment]
> @lala-laura is there are a reason to have different classes for the nav section (ex. `nav-home`, `nav-book`)? You only need one class that can be used throughout.

Yes, I understand that one class can be used throughout. I added them when after seeing the navigation not show on those pages, so they are there in case it's needed. They'd be removed if that wasn't the case.

**Comment by lala-laura** [comment]
> @lala-laura I would suggest a couple things before this is pushed:
> 
> 1. set standard widths for the links in your nav bar so you don't have the jitter with the hover effect, and so that contact isn't pushed all the way to the edge.
> 2. We are thinking of adding hero images to the pages that the nav bar isn't showing up on, so just copy the code you have for the about page to make it show on those ones.  We can go in and change the titles and images later, but just updating the title would be nice to have when you do that transition.
> 3. I think it would be nice to have the active links page bolded. So for example, when you're on booking the booking link is bolded and not just when hovered on. You can do that with a class and assign it to the specific link for the pages your on.
> 
> Let me know if you have any questions on this, I'm available for a call if you'd like to touch base.

I don't have any notes saying anything about adding hero imgs to those pages so I'll look at that tomorrow, along with the rest, unless I can get to it later tonight.

**Comment by loganmorganml1** [comment]
> > @lala-laura I would suggest a couple things before this is pushed:
> > 
> > 1. set standard widths for the links in your nav bar so you don't have the jitter with the hover effect, and so that contact isn't pushed all the way to the edge.
> > 2. We are thinking of adding hero images to the pages that the nav bar isn't showing up on, so just copy the code you have for the about page to make it show on those ones.  We can go in and change the titles and images later, but just updating the title would be nice to have when you do that transition.
> > 3. I think it would be nice to have the active links page bolded. So for example, when you're on booking the booking link is bolded and not just when hovered on. You can do that with a class and assign it to the specific link for the pages your on.
> > 
> > Let me know if you have any questions on this, I'm available for a call if you'd like to touch base.
> 
> I don't have any notes saying anything about adding hero imgs to those pages so I'll look at that tomorrow, along with the rest, unless I can get to it later tonight.

in my booking styling branch I had added one. I'll update the code and re-submit the pull request since theres seems to be some issues since it's so far behind now

**Comment by loganmorganml1** [comment]
@lala-laura sorry Laura just letting you know I resolved a conflict with your code and the main but saw you changed the pull request to draft 18 seconds ago after I did that. Just letting you know in case you have to pull.

@loganmorganml1 okay, that's fine, thanks. I didn't see you merged until after I set it to draft. I'll pull the changes when I get back over to it

**Comment by loganmorganml1** [comment]
@lala-laura Also just letting you know in the about page on the main it looks like there is duplicate code for the nav. We can resolve that either with this branch or another update one, but either way I'll wait until this branch is merged before updating that with any other branches.

**Comment by loganmorganml1** [comment]
> @lala-laura sorry Laura just letting you know I resolved a conflict with your code and the main but saw you changed the pull request to draft 18 seconds ago after I did that. Just letting you know in case you have to pull.
> 
> @loganmorganml1 okay, that's fine, thanks. I didn't see you merged until after I set it to draft. I'll pull the changes when I get back over to it

No worries it was literally nothing -- like no additional code that was added or deleted just two empty lines lol. But it will still probably need you to pull.

**Comment by techeduk8r** [comment]
I am not sure where the two of you are on this, but looking at it right now, the link text still jumps and the entire-form-content and other-popular-grid are overlapping. It is unclear which changes caused the overlap. 

@techeduk8r 
I'm making a lot of fixes and edits, so you might have seen some awkward formatting that is being adjusted

**Review by loganmorganml1 — APPROVED** [review]
Looks good!

**Pull request merged**
